# Generated by Django 5.2.8 on 2025-11-23 05:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='userdetails',
            name='phone',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
