# Generated by Django 5.2.8 on 2025-11-24 13:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_order_order_id_orderitem'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='item_name',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='order',
            name='qty',
            field=models.TextField(default=''),
        ),
        migrations.DeleteModel(
            name='OrderItem',
        ),
    ]
